apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: cloudru
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: mega6obep/cloudru-app:latest
          ports:
            - containerPort: 8000
          env:
            - name: AUTHOR
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: AUTHOR
            - name: UUID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_ENV
          readinessProbe:
            httpGet:
              path: /hostname
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /hostname
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20