apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: cloudru
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP